// <auto-generated />
using System;
using InventoryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922094717_AddUserEntity")]
    partial class AddUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("InventoryApp.Entities.Accessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VerifiedDirectly")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("Accessories");
                });

            modelBuilder.Entity("InventoryApp.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NetBookValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PurchaseValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponsiblePersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StatusChangedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("InventoryZoneId");

                    b.HasIndex("ResponsiblePersonId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("InventoryApp.Entities.AssetCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CodeType", "CodeValue");

                    b.ToTable("AssetCodes");
                });

            modelBuilder.Entity("InventoryApp.Entities.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssetTypes");
                });

            modelBuilder.Entity("InventoryApp.Entities.InventoryPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryZoneId");

                    b.ToTable("InventoryPeriods");
                });

            modelBuilder.Entity("InventoryApp.Entities.InventoryZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("InventoryZones");
                });

            modelBuilder.Entity("InventoryApp.Entities.ResponsiblePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResponsiblePersons");
                });

            modelBuilder.Entity("InventoryApp.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryZoneId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("InventoryApp.Entities.Scan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScannedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("InventoryPeriodId");

                    b.HasIndex("InventoryZoneId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("InventoryApp.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponsiblePersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResponsiblePersonId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InventoryApp.Entities.Accessory", b =>
                {
                    b.HasOne("InventoryApp.Entities.Asset", "Asset")
                        .WithMany("Accessories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("InventoryApp.Entities.Asset", b =>
                {
                    b.HasOne("InventoryApp.Entities.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryApp.Entities.InventoryZone", "InventoryZone")
                        .WithMany("Assets")
                        .HasForeignKey("InventoryZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryApp.Entities.ResponsiblePerson", "ResponsiblePerson")
                        .WithMany("Assets")
                        .HasForeignKey("ResponsiblePersonId");

                    b.Navigation("AssetType");

                    b.Navigation("InventoryZone");

                    b.Navigation("ResponsiblePerson");
                });

            modelBuilder.Entity("InventoryApp.Entities.AssetCode", b =>
                {
                    b.HasOne("InventoryApp.Entities.Asset", "Asset")
                        .WithMany("Codes")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("InventoryApp.Entities.InventoryPeriod", b =>
                {
                    b.HasOne("InventoryApp.Entities.InventoryZone", "InventoryZone")
                        .WithMany("InventoryPeriods")
                        .HasForeignKey("InventoryZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryZone");
                });

            modelBuilder.Entity("InventoryApp.Entities.Room", b =>
                {
                    b.HasOne("InventoryApp.Entities.InventoryZone", "InventoryZone")
                        .WithMany("Rooms")
                        .HasForeignKey("InventoryZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryZone");
                });

            modelBuilder.Entity("InventoryApp.Entities.Scan", b =>
                {
                    b.HasOne("InventoryApp.Entities.Asset", "Asset")
                        .WithMany("Scans")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryApp.Entities.InventoryPeriod", "InventoryPeriod")
                        .WithMany("Scans")
                        .HasForeignKey("InventoryPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryApp.Entities.InventoryZone", "InventoryZone")
                        .WithMany()
                        .HasForeignKey("InventoryZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryApp.Entities.Room", "Room")
                        .WithMany("Scans")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryApp.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("InventoryPeriod");

                    b.Navigation("InventoryZone");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryApp.Entities.User", b =>
                {
                    b.HasOne("InventoryApp.Entities.ResponsiblePerson", "ResponsiblePerson")
                        .WithMany()
                        .HasForeignKey("ResponsiblePersonId");

                    b.Navigation("ResponsiblePerson");
                });

            modelBuilder.Entity("InventoryApp.Entities.Asset", b =>
                {
                    b.Navigation("Accessories");

                    b.Navigation("Codes");

                    b.Navigation("Scans");
                });

            modelBuilder.Entity("InventoryApp.Entities.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("InventoryApp.Entities.InventoryPeriod", b =>
                {
                    b.Navigation("Scans");
                });

            modelBuilder.Entity("InventoryApp.Entities.InventoryZone", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("InventoryPeriods");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("InventoryApp.Entities.ResponsiblePerson", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("InventoryApp.Entities.Room", b =>
                {
                    b.Navigation("Scans");
                });
#pragma warning restore 612, 618
        }
    }
}
